import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, huntingcoder blog, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainnav}>
        <ul>
          <Link href="/">
            <li>Home</li>
          </Link>
          <Link href="/about">
            <li>About</li>
          </Link>
          <Link href="/blog">
            <li>Blog</li>
          </Link>
          <Link href="/contact">
            <li>Contact</li>
          </Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>Hunting coder</h1>
         <div className={styles.imagewrap}>
          {/* <Image className={styles.myImg} src="/homeimg.jfif" width={237} height={158}/> */}
          <img className={styles.myImg} src="/homeimg.jfif" width={237} height={158} alt="hunting coder" />
        </div>
        <p className={styles.description}>
          A blog for hunting coders by krushik Bairaboina
        </p>
        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn Javascript in 2024?</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2024?</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2024?</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2024?</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
